### ISSUE TITLE
Provide flip combinators

### ISSUE THREAD

**Issue by singpolyma** [ekmett/either#10]
This package has a set of handy functions for working with Either, I propose the following be added:

    flipE :: Either a b -> Either b a
    flipET :: EitherT a m b -> EitherT b m a

**Comment by andrewthad** [comment]
Bump. I would expect to find these in `Data.Either.Combinators`, but I would prefer them to be named `flipEither` and `flipEitherT` instead.

**Comment by phaazon** [comment]
Provided as `swapEither` and `swapEitherT` as @ekmett thinks *flip* is for function whereast `swap` is for bifunctors, and now that makes sense to me as well. :)

**Comment by RyanGlScott** [comment]
Looks like this was resolved by #37.
