### ISSUE TITLE
Dependency explosion -> dependency hell

### ISSUE THREAD

**Issue by AaronFriel** [ekmett/either#17]
Doing a "cabal install either" on a clean system or in a sandbox results in an explosion of imported dependencies:
- MonadRandom-0.1.12
- base-unicode-symbols-0.2.2.4
- comonad-4.0
- contravariant-0.4.4
- distributive-0.4
- either-4.1
- hashable-1.2.1.0
- monad-control-0.3.2.2
- nats-0.1.2
- semigroupoids-4.0
- semigroups-0.12.2
- tagged-0.7
- text-1.1.0.0
- transformers-base-0.4.1
- transformers-compat-0.1.1.1
- unordered-containers-0.2.3.3

I think this ought to be reduced. The dependency explosion has a high likelihood of causing Cabal dependency hell if `either` is innocuously installed prior to other, more sophisticated packages. For example:

```
$ cabal sandbox init
...
$ cabal install either
...
$ cabal install yesod-platform --dry-run
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: MonadRandom-0.1.12/installed-607... (user goal)
trying: random-1.0.1.1/installed-326... (dependency of
MonadRandom-0.1.12/installed-607...)
trying: time-1.4.1/installed-978... (dependency of
random-1.0.1.1/installed-326...)
trying: deepseq-1.3.0.2/installed-0f5... (dependency of
time-1.4.1/installed-978...)
next goal: yesod-platform (user goal)
rejecting: yesod-platform-1.2.7.1, 1.2.7 (conflict: either =>
monad-control==0.3.2.2/installed-b78..., yesod-platform =>
monad-control==0.3.2.3)
trying: yesod-platform-1.2.6.1
next goal: language-javascript (dependency of yesod-platform-1.2.6.1)
rejecting: language-javascript-0.5.9 (conflict: yesod-platform =>
language-javascript==0.5.8)
rejecting: language-javascript-0.5.8 (conflict: deepseq =>
array==0.5.0.0/installed-b8e..., language-javascript => array>=0.3 && <0.5)
rejecting: language-javascript-0.5.7, 0.5.6, 0.5.5, 0.5.4, 0.5.3, 0.5.2,
0.5.1, 0.5.0, 0.4.10, 0.4.9, 0.4.8, 0.4.7, 0.4.6, 0.4.5, 0.4.4, 0.4.3, 0.4.2,
0.4.1, 0.4.0, 0.3.0, 0.2.2, 0.2.1, 0.2.0, 0.1.0, 0.0.3, 0.0.2, 0.0.1
(conflict: yesod-platform => language-javascript==0.5.8)
Backjump limit reached (change with --max-backjumps).

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

**Comment by bos** [comment]
This also almost doubles the number of dependencies needed by `criterion` (see bos/criterion#67). @xich submitted a pull request to drop use of `either`, but that has its own problems: it pulls in an extremely new version of `mtl`.

**Comment by bos** [comment]
It looks like a dependency on `transformers-compat` instead of `either` solved my problem.

**Comment by phaazon** [comment]
You shouldn’t care about those dependencies IMHO. They are very likely to be installed anyway.

**Comment by ekmett** [comment]
Resolved by ultimately removing the `EitherT` type from this package. The dependency surface is much smaller now.
