### ISSUE TITLE
Document why the EitherT instance throws exceptions into the base monad.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [ekmett/either#21]
I was surprised by the definition of this instance:

```
 MonadThrow m => MonadThrow (EitherT e m)   
```

It is documented what it does, but it would be great if there was some additional documentation (link to blog post for example) for why this is a reasonable choice and how EitherT as for example used in the Script type in errors should be integrated with code that uses MonadThrow (such as conduit).

**Comment by ekmett** [comment]
Solved by the steady march of time. EitherT no longer exists in HEAD. =)
