### ISSUE TITLE
either depends on template-haskell

### ISSUE THREAD

**Issue by Dfgkkk555** [ekmett/either#24]
Since 4.3 `either` depends on `free`, which in turns depends on `template-haskell`.
This causes problems with, e.g., compiling haskell to javascript using `haste`.

Do you think it is possible to live without `free`? `template-haskell` is and always will be a pain to deal with in these situations.

**Comment by glguy** [comment]
The `free` package merely depends on `template-haskell`, it does not use the extension that I can see.

**Comment by ekmett** [comment]
Since it isn't actually using the extension it should install fine on stage1 platforms.
