### ISSUE TITLE
MFunctor/MMonad instance for EitherT?

### ISSUE THREAD

**Issue by Gabriel439** [ekmett/either#4]
I'm only asking because somebody raised this issue on `pipes`:

https://github.com/Gabriel439/Haskell-Pipes-Library/issues/26

The alternative is that `EitherT` gets merged into transformers, in which case I add the instances to `mmorph`.  Do you know what the status on that is?

**Comment by RyanGlScott** [comment]
Update: #39 added an `MFunctor (EitherT e)` instance. @Gabriel439, do you still wish to add an `MMonad` instance?

**Comment by Gabriel439** [comment]
@RyanGlScott Whatever the maintainers prefer.  Right now I lean on `ExceptT` more heavily (despite the fact that I don't like the name at all) so this is less urgent to me, but there seems to be no harm in adding an `MMonad` instance if there's already an `MFunctor` instance (other than bloating the instance list a bit :) )

**Comment by ekmett** [comment]
Just in time for us to remove `EitherT` entirely. ;)
