### ISSUE TITLE
Missing MonadMask instance?

### ISSUE THREAD

**Issue by edsko** [ekmett/either#41]
Is there a reason why there is no `MonadMask` instance? It seems it's easily defined:

``` haskell
instance MonadMask m => MonadMask (EitherT err m) where
  mask act = EitherT $ mask $ \restore ->
    runEitherT $ act (EitherT . restore . runEitherT)

  uninterruptibleMask act = EitherT $ uninterruptibleMask $ \restore ->
    runEitherT $ act (EitherT . restore . runEitherT)
```

**Comment by RyanGlScott** [comment]
See [this `exceptions` issue](https://github.com/ekmett/exceptions/pull/45) for an explanation for why a `MonadMask` instance isn't defined for `ExceptT` (the `transformers` equivalent of `EitherT`).

__tl;dr__ There are multiple exit paths for exceptions thrown from a monad transformer stack involving `ExceptT`, so you can't guarantee that certain actions are run in the presence of exceptions.

**Comment by edsko** [comment]
So I've read [the issue](https://github.com/ekmett/exceptions/pull/45) as well as the [blog post](http://www.yesodweb.com/blog/2014/06/exceptions-transformers) linked from it but I'm still scratching my head a little.. is the issue that if we do something like

``` haskell
test1 :: IO (Either IOException ())
test1 = runEitherT $ 
    left (userError "uhoh") 
  `finally` 
    lift (putStrLn "Cleaning up")
```

that cleanup handler does not get called, but if we do

``` haskell
test2 :: IO (Either IOException ())
test2 = runEitherT $
    throwM (userError "uhoh") 
  `finally` 
    lift (putStrLn "Cleaning up")
```

the cleanup handler _does_ get called? While that is unfortunate, I don't really see what's this got to do with masking. After all, one could equally complain that the exception handler in

``` haskell
test3 :: IO (Either IOException ())
test3 = runEitherT $
    left (userError "uhoh") 
  `catchAll` \_ ->
    lift (putStrLn "Caught exception!")
```

does not get called, but the exception handler in 

``` haskell
test4 :: IO (Either IOException ())
test4 = runEitherT $
    throwM (userError "uhoh") 
  `catchAll` \_ ->
    lift (putStrLn "Caught exception!")
```

does.. So I guess I'm still missing the point here :flushed:

**Comment by edsko** [comment]
Hmm I suppose it's just by definition of the `MonadMask` class, which stipulates that

> Instances should ensure that, in the following code:
>
> ``` haskell
> f `finally` g
> ```
>
> The action g is called regardless of what occurs within f, including async exceptions.

It still feels a bit arbitrary to me to impose this on `MonadMask` and say that the `MonadCatch` instance is okay, but fair enough.
