### ISSUE TITLE
Monad instance for Validation

### ISSUE THREAD

**Issue by tdietert** [ekmett/either#47]
I am using Data.Either.Validation in some front-end work with form validation using FRP and was surprised that I couldn't write this function:

`validateNames names = fmap head . sequence <$> mapM validateName names`

where

`validateName :: Text -> IO (Validation VError VSuccess)` 

Is there some reason that `Validation e a` doesn't have a monad instance? I had to resort to using `validationToEither` and `eitherToValidation`, which is not that bad, but I was wondering why, if `Either` and `Validation` are isomorphic, `Validation` doesn't have a monad instance.

Please ignore my _seemingly_ unsafe use of `head` (which really isn't unsafe, because I'm using a case statement to check if `names` is not an empty list).

**Comment by ekmett** [comment]
Yes. `Validation` doesn't have a `Monad` that is compatible with its `Applicative`. This is why it isn't simply the definition we use for `Either`. Whether you `mapM` or `traverse` should never affect your answer, and allowing such here would cause that reasoning to fail.

**Comment by bitemyapp** [comment]
@tdietert makes you feel any better, I faceplanted into this too :)

**Comment by blamario** [comment]
A module containing only the `Monad` instance and an explanation (perhaps a warning) might be of some benefit. There are legitimate uses for such an instance. Think of compilation errors: we don't always care that all errors are presented, even if more is generally better.
