### ISSUE TITLE
Validation Alternative breaks right identity law

### ISSUE THREAD

**Issue by gwils** [ekmett/either#50]
`Failure "x" <|> empty` should be `Failure "x"` but it is `empty` (`Failure ""`)

The Alt and `<|>` bias in the failure case, hence are not collecting in the semigroup. But the `empty` is for a non-biased collecting failure case. They do not agree. We should pick a side.

The options as I see them are a biased, non-collecting `Alt`, that does not have an `Alternative`, or a collecting Alt to match the current monoidish Alternative.

My vote is to keep the biased, non-collecting `Alt`, and delete the `Alternative`. The collecting instance does not satisfy the right distributive law, which we might care about depending on what we think `Alternative` means.

**Comment by ekmett** [comment]
I confess I'm torn on this one.

I think the intention of the code here was to provide a collecting Alternative.

That way you could do things like `asum` over a bunch of code try try to run as much of it as possible and accumulate all of the errors.

Giving up the Alternative screws that up.

It seems to me that the Alt instance is the broken thing here, which then accidentally broke the Alternative.

**Comment by bitemyapp** [comment]
This was convincing to me, what do you think @gwils?

**Comment by gwils** [comment]
The important thing is that we make a decision one way or the other. I'm fine with lensing back and forward to Either to get the Alt instance I want.

Thinking about it, we might as well hang the collecting instance here just so that you can get at it if you need to.
I think I'm convinced too.

**Comment by ekmett** [comment]
Alright, then let's do that. Switch to a collecting `Alt`, which will fix the `Alternative`.

@gwils: You now have full access to do what you need here and to upload a new version to hackage. You have the power. =)

**Comment by ekmett** [comment]
Ok, I took some of that power away and actually made the change. ;)
