### ISSUE TITLE
`EitherT` and `transformers`

### ISSUE THREAD

**Issue by Gabriel439** [ekmett/either#7]
I would like to either get `EitherT` into transformers or remove the `Error` constraint from `ErrorT`.  I'm beginning the discussion here before bringing it up on libraries so we can sort out any issues beforehand.

The advantages of just removing the constraint are:
- It's mostly backwards compatible

The disadvantages are:
- I think `EitherT` is a better name for the abstraction
- This will silently break code that depends on `fail` for proper error messages

I think removing the constraint is probably the most realistic solution, but I think the biggest risk if we bring it up on libraries is that this will revive the discussion about `fail` being a part of `Monad` and sidetrack things.

I would like to know your thoughts.

**Comment by RyanGlScott** [comment]
What is the current state of this issue now that `transformers-compat` (and in particular, its backport for `ExceptT`) has seen wide adoption?

**Comment by ekmett** [comment]
My intention had been to deprecate `EitherT` once `transformers` 0.5 had a wider adoption around GHC 8.4 or so.

We COULD simply switch to recommending `transformers-compat`, though.

**Comment by snoyberg** [comment]
I have no problem recommending `transformers-compat`, and have no particular horse in this race. I'll follow your lead on what to recommend to people @ekmett.

**Comment by ekmett** [comment]
Let's move this timeline up to 8.2.

**Comment by sjakobi** [comment]
What's the status of this issue now that GHC-8.2 has been released?

**Comment by ekmett** [comment]
Then I'd say its time to deprecate EitherT.
